name: .NET

on:
  push:
    tags:
    - *
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Download HKToolUtils
      run: |
        wget https://github.com/HKLab/HKToolUtils/releases/download/v1.0.0.0/net5.zip -O HKToolUtils.zip
        unzip HKToolUtils.zip -d HKToolUtils
    - name: Build
      run: |
        dotnet ./HKToolUtils/HKToolUtils.dll build .
    - name: Zip
      run: |
        zip -jr DCParry.zip ./Output
    - name: Release
      uses: softprops/action-gh-release@v1
      with: |
        body: Release
        files:
          ./DCParry.zip
